"""empty message

Revision ID: 17f4fd0dfeff
Revises: 1a7aabf4d785
Create Date: 2022-11-29 23:47:14.276424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f4fd0dfeff'
down_revision = '1a7aabf4d785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imgs', 'mimetype')
    op.drop_column('imgs', 'name')
    op.create_foreign_key(None, 'userprofile', 'imgs', ['profile_picture_id'], ['id'])
    op.drop_column('userprofile', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('profile_picture', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'userprofile', type_='foreignkey')
    op.add_column('imgs', sa.Column('name', sa.TEXT(), nullable=False))
    op.add_column('imgs', sa.Column('mimetype', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
