"""empty message

Revision ID: 1a0ae8d9c5ba
Revises: 17f4fd0dfeff
Create Date: 2022-11-29 23:49:40.932193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0ae8d9c5ba'
down_revision = '17f4fd0dfeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imgs', 'name')
    op.drop_column('imgs', 'mimetype')
    op.create_foreign_key(None, 'userprofile', 'imgs', ['profile_picture_id'], ['id'])
    op.drop_column('userprofile', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('profile_picture', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'userprofile', type_='foreignkey')
    op.add_column('imgs', sa.Column('mimetype', sa.TEXT(), nullable=False))
    op.add_column('imgs', sa.Column('name', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
