"""empty message

Revision ID: 1a7aabf4d785
Revises: 27740827874c
Create Date: 2022-11-28 23:08:23.971703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7aabf4d785'
down_revision = '27740827874c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.add_column('userprofile', sa.Column('profile_picture_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userprofile', 'imgs', ['profile_picture_id'], ['id'])
    op.drop_column('userprofile', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('profile_picture', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'userprofile', type_='foreignkey')
    op.drop_column('userprofile', 'profile_picture_id')
    op.drop_table('imgs')
    # ### end Alembic commands ###
