"""empty message

Revision ID: 2f63304f57bf
Revises: fb802e7eb839
Create Date: 2023-05-06 22:22:48.406971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f63304f57bf'
down_revision = 'fb802e7eb839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'actions', ['action'])
    op.create_unique_constraint(None, 'actions', ['id'])
    op.create_unique_constraint(None, 'badge', ['id'])
    op.create_unique_constraint(None, 'badge', ['name'])
    op.add_column('golflog', sa.Column('points', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'golflog', ['id'])
    op.create_foreign_key(None, 'golflog', 'satisfactions', ['satisfaction_level_id'], ['id'])
    op.create_unique_constraint(None, 'user_badges', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_badges', type_='unique')
    op.drop_constraint(None, 'golflog', type_='foreignkey')
    op.drop_constraint(None, 'golflog', type_='unique')
    op.drop_column('golflog', 'points')
    op.drop_constraint(None, 'badge', type_='unique')
    op.drop_constraint(None, 'badge', type_='unique')
    op.drop_constraint(None, 'actions', type_='unique')
    op.drop_constraint(None, 'actions', type_='unique')
    # ### end Alembic commands ###
