"""empty message

Revision ID: 5bb8f8e58c84
Revises: 049818e8b0ae
Create Date: 2023-02-03 19:41:22.350492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb8f8e58c84'
down_revision = '049818e8b0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supports_email'), 'supports', ['email'], unique=False)
    op.create_index(op.f('ix_supports_timestamp'), 'supports', ['timestamp'], unique=False)
    op.create_index(op.f('ix_supports_username'), 'supports', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supports_username'), table_name='supports')
    op.drop_index(op.f('ix_supports_timestamp'), table_name='supports')
    op.drop_index(op.f('ix_supports_email'), table_name='supports')
    op.drop_table('supports')
    # ### end Alembic commands ###
