"""empty message

Revision ID: 5fa2e251275f
Revises: 
Create Date: 2022-11-09 21:58:05.109686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa2e251275f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=64), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
