"""empty message

Revision ID: d4655d61e960
Revises: 6860efd93c66
Create Date: 2022-11-21 15:37:24.468897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4655d61e960'
down_revision = '6860efd93c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drinking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drinking', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handicap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handicap', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playing_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playing_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ride_or_walk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_or_walk', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smoking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smoking', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('time_of_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('time_of_day_id', sa.Integer(), nullable=True),
    sa.Column('ride_or_walk_id', sa.Integer(), nullable=True),
    sa.Column('handicap_id', sa.Integer(), nullable=True),
    sa.Column('smoking_id', sa.Integer(), nullable=True),
    sa.Column('drinking_id', sa.Integer(), nullable=True),
    sa.Column('playing_type_id', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('location')
    op.drop_column('users', 'day_id')
    op.drop_column('users', 'city')
    op.drop_column('users', 'time_of_day_id')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'alcohol_id')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'state')
    op.drop_column('users', 'playing_type')
    op.drop_column('users', 'ride_or_walk_id')
    op.drop_column('users', 'smoking_id')
    op.drop_column('users', 'handicap_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('handicap_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('smoking_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('ride_or_walk_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('playing_type', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('state', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('bio', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('alcohol_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('time_of_day_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=64), nullable=True))
    op.add_column('users', sa.Column('day_id', sa.INTEGER(), nullable=True))
    op.create_table('location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('state', sa.VARCHAR(length=64), nullable=True),
    sa.Column('location_id', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_profile')
    op.drop_table('time_of_day')
    op.drop_table('state')
    op.drop_table('smoking')
    op.drop_table('ride_or_walk')
    op.drop_table('playing_type')
    op.drop_table('handicap')
    op.drop_table('gender')
    op.drop_table('drinking')
    op.drop_table('day')
    op.drop_table('city')
    # ### end Alembic commands ###
