"""empty message

Revision ID: e8252e0a63fb
Revises: d9fc258f0445
Create Date: 2022-11-10 22:24:38.803542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8252e0a63fb'
down_revision = 'd9fc258f0445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('day_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'status_id')
    op.drop_column('users', 'frequency_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('frequency_id', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('status_id', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'day_id')
    # ### end Alembic commands ###
