"""empty message

Revision ID: fb802e7eb839
Revises: 0960a29c9551
Create Date: 2023-05-03 21:30:58.462948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb802e7eb839'
down_revision = '0960a29c9551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satisfactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satisfaction', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('satisfaction')
    )
    op.create_unique_constraint(None, 'actions', ['action'])
    op.create_unique_constraint(None, 'actions', ['id'])
    op.create_unique_constraint(None, 'badge', ['id'])
    op.create_unique_constraint(None, 'badge', ['name'])
    op.create_unique_constraint(None, 'golflog', ['id'])
    op.create_unique_constraint(None, 'user_badges', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_badges', type_='unique')
    op.drop_constraint(None, 'golflog', type_='unique')
    op.drop_constraint(None, 'badge', type_='unique')
    op.drop_constraint(None, 'badge', type_='unique')
    op.drop_constraint(None, 'actions', type_='unique')
    op.drop_constraint(None, 'actions', type_='unique')
    op.drop_table('satisfactions')
    # ### end Alembic commands ###
